-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "annualRevenue" TEXT,
ADD COLUMN     "businessCategory" TEXT,
ADD COLUMN     "businessDescription" TEXT,
ADD COLUMN     "businessHours" JSONB,
ADD COLUMN     "businessLicense" TEXT,
ADD COLUMN     "businessSubcategory" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "country" TEXT,
ADD COLUMN     "employeeCount" TEXT,
ADD COLUMN     "foundedYear" INTEGER,
ADD COLUMN     "latitude" DOUBLE PRECISION,
ADD COLUMN     "longitude" DOUBLE PRECISION,
ADD COLUMN     "postalCode" TEXT,
ADD COLUMN     "primaryProducts" JSONB,
ADD COLUMN     "secondaryProducts" JSONB,
ADD COLUMN     "socialMedia" JSONB,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "taxId" TEXT,
ADD COLUMN     "website" TEXT,
ALTER COLUMN "currency" SET DEFAULT 'KES',
ALTER COLUMN "timezone" SET DEFAULT 'Africa/Nairobi';
